# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('sex', models.SmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')])),
                ('status', models.SmallIntegerField(choices=[(0, 'NORMAL'), (1, 'DISABLED')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
